"""add transfers core

Revision ID: 4248666d5b14
Revises: d1946c2ceb15
Create Date: 2026-01-20 22:54:06.804820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4248666d5b14'
down_revision: Union[str, Sequence[str], None] = 'd1946c2ceb15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current_stock',
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('on_hand_qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('warehouse_id', 'material_id')
    )
    op.create_table('transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_warehouse_id', sa.Integer(), nullable=False),
    sa.Column('to_warehouse_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('planned_qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('storekeeper_from_id', sa.Integer(), nullable=True),
    sa.Column('storekeeper_to_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('seal_number', sa.String(length=100), nullable=True),
    sa.Column('deadline_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('from_warehouse_id<>to_warehouse_id', name='ck_transfers_from_to_diff'),
    sa.CheckConstraint('planned_qty>0', name='ck_transfers_planned_qty_positive'),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['from_warehouse_id'], ['warehouses.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['storekeeper_from_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['storekeeper_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['to_warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transfer_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transfer_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transfer_events')
    op.drop_table('transfers')
    op.drop_table('current_stock')
    # ### end Alembic commands ###
