"""add transfer qty facts

Revision ID: 9818df918c2a
Revises: 32ca04f29842
Create Date: 2026-01-26 23:46:03.918732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9818df918c2a'
down_revision: Union[str, Sequence[str], None] = '32ca04f29842'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Column("shipped_qty", sa.Numeric(12, 3), nullable=False, server_default="0"),
    sa.Column("received_qty", sa.Numeric(12, 3), nullable=False, server_default="0"),
    sa.Column("damaged_qty", sa.Numeric(12, 3), nullable=False, server_default="0"),
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transfers', 'damaged_qty')
    op.drop_column('transfers', 'received_qty')
    op.drop_column('transfers', 'shipped_qty')
    # ### end Alembic commands ###
